# Generated by Django 6.0.1 on 2026-03-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='categorie',
            field=models.CharField(default='Plat', max_length=50),
        ),
    ]
