# Generated by Django 6.0.1 on 2026-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_plat_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='categorie',
            field=models.CharField(choices=[('Plats', 'Plats'), ('Desserts', 'Desserts'), ('Boissons', 'Boissons')], default='Plats', max_length=50),
        ),
    ]
