# Generated by Django 6.0.1 on 2026-03-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_alter_plat_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='categorie',
            field=models.CharField(choices=[('Plat', 'Plat'), ('Dessert', 'Dessert'), ('Boisson', 'Boisson')], default='Plats', max_length=50),
        ),
    ]
